from os import getenv


CHROMEDRIVER_PATH = getenv("CHROMEDRIVER_PATH")
GOOGLE_CHROME_BIN = getenv("GOOGLE_CHROME_BIN")
SLEEP_SECONDS = int(getenv("SLEEP_SECONDS"))
GIVEAWAY_PARTICIPATIONS = int(getenv("GIVEAWAY_PARTICIPATIONS"))
DISCORD = getenv("DISCORD")
TWITTER = getenv("TWITTER")
